name: Build

on:
  pull_request:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout Aliucord
        uses: actions/checkout@master
        with:
          repository: "Aliucord/Aliucord"
          path: "repo"

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          chmod +x gradlew
          ./gradlew make generateUpdaterJson

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: 'build/*.zip'
